### ISSUE TITLE
Move directories broke after 0.13.3.

### ISSUE THREAD

**Issue by cybercatgurrl** [Nexus-Mods/Vortex#102]
Any time I try to move the mod folder for a game from the C: default to another drive after 0.13.3 it fails.

**Comment by twist3dimages** [comment]
What's it saying? I'm getting errors too but if you want his help you gotta give some error messages, screenshots, something lol

**Comment by darthbdaman** [comment]
This worked for me with Skyrim SE, but with Dragon Age I get I get a failed to move directories notification, with the following error message.

`Error: failed to run deployment helper
    at elevated.default.then.then (D:\Vortex\resources\app.asar\extensions\symlink_activator_elevate\index.js:152:28)
    at tryCatcher (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at <anonymous>`

**Comment by TanninOne** [comment]
"failed to run deployment helper" is a known bug,  will be fixed in 0.13.6

**Comment by TanninOne** [comment]
should be fixed in the meantime
