### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'reduce')

### ISSUE THREAD

**Issue by wildman309** [Nexus-Mods/Vortex#11097]
So I admit I'm pretty new at this but I'm trying to mod the witcher 3 through the vortex and I've tried reinstalling everything but I'm still getting this error

TypeError: Cannot read properties of undefined (reading 'reduce')
    at D:\Vortex Mods\resources\app.asar.unpacked\bundledPlugins\game-witcher3\mergeInventoryParsing.js:51:68
    at Generator.next (<anonymous>)
    at D:\Vortex Mods\resources\app.asar.unpacked\bundledPlugins\game-witcher3\mergeInventoryParsing.js:8:71
    at Promise.cancellationExecute [as _execute] (D:\Vortex Mods\resources\app.asar\node_modules\bluebird\js\release\debuggability.js:406:9)
    at Promise._resolveFromExecutor (D:\Vortex Mods\resources\app.asar\node_modules\bluebird\js\release\promise.js:518:18)
    at new Promise (D:\Vortex Mods\resources\app.asar\node_modules\bluebird\js\release\promise.js:103:10)
    at __awaiter (D:\Vortex Mods\resources\app.asar.unpacked\bundledPlugins\game-witcher3\mergeInventoryParsing.js:4:12)
    at D:\Vortex Mods\resources\app.asar.unpacked\bundledPlugins\game-witcher3\mergeInventoryParsing.js:44:35
    at tryCatcher (D:\Vortex Mods\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Vortex Mods\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\Vortex Mods\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Vortex Mods\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Vortex Mods\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\Vortex Mods\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\Vortex Mods\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\Vortex Mods\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)

**Comment by IDCs** [comment]
Hi there - I've improved our error handling of invalid script merger inventory file but would still be good to see what your `mergeinventory.xml` file looks like - you can find it inside the script merger's directory - please send it to us using the "Attach Files" dropdown button.

**Comment by IDCs** [comment]
@wildman309 - can you please send us your `mergeinventory.xml` file which can be found inside the script merger's directory.

**Comment by IDCs** [comment]
closing due to lack of feedback
