### ISSUE TITLE
Download of collections not working (Invalid URL)

### ISSUE THREAD

**Issue by Molgorian** [Nexus-Mods/Vortex#12011]
This error occurs with all Stardew Valley collection downloads. Download of individual mods works without problems

DataInvalid: invalid nxm url "nxm://stardewvalley/collections/g14kxi/revisions/2"
    at new NXMUrl (E:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:2653:72)
    at E:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:5800:144
    at E:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:2802:61
    at tryCatcher (E:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (E:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (E:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (E:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (E:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)

**Comment by Molgorian** [comment]
wrong version..., fixed
