### ISSUE TITLE
Vortex not updating extensions, Invalid Extension

### ISSUE THREAD

**Issue by Alatarius** [Nexus-Mods/Vortex#12202]
**Describe the bug**
Error reads Invalid Extension
Extension needs to include index.js and info.json on top-level

**To Reproduce**
1. start vortex
2. read error in notifications
3. See error

**Expected behavior**
Unsure what was supposed to be expected behavior

**Platform (please complete the following information):**
 - OS: win32 x64 (6.1.7601)
 - Vortex Version 1.5.13

**Additional context**
This is a copy/paste of the error log:

DataInvalid: Extension needs to include index.js and info.json on top-level
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:2465:34
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\catch_filter.js:34:37
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)

**Comment by IDCs** [comment]
You have a corrupt extension in your `%appdata%/vortex/plugins` directory - make sure all the extensions in that directory have a valid `index.js` and `info.json` file. Any that are invalid should be deleted.

This can happen if an extension download gets corrupted somehow or a manual installation gone wrong.
