### ISSUE TITLE
Error: Plugins not sorted because "WeightLess.esp"is not a valid plugin/ failed to parse plugins

### ISSUE THREAD

**Issue by ThatWentWell17** [Nexus-Mods/Vortex#12333]
error details: 

Error: "weightless.esp" is not a valid plugin
    at l.handleResponse (G:\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:2:619591)
    at G:\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:2:618064
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (G:\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:2:618047)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

Occurred when running the SSEEdit script 'Weightless.pas' for the 'WeightLess' mod

running on Windows 10 x64, Vortex 1.6.1

**Comment by ThatWentWell17** [comment]
Another error, obtained when running the xEdit script while having disabled Insects Be Gone

Error: "weightless.esp" is not a valid plugin

    at l.handleResponse (G:\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:2:619591)
    at G:\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:2:618064
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (G:\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:2:618047)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)

**Comment by IDCs** [comment]
You used external tools to edit that plugin. Vortex simply relays the information give to us by LOOT - whatever you did to that plugin has rendered it invalid. Redownload it.
