### ISSUE TITLE
Cannot read properties of undefined (reading 'modInfo')

### ISSUE THREAD

**Issue by Jackrascal** [Nexus-Mods/Vortex#12937]
TypeError: Cannot read properties of undefined (reading 'modInfo')
    at C:\Users\NITRO5\AppData\Roaming\Vortex\plugins\Vortex Extension Update - Vortex Steam File Downloader v0.1.1\index.js:11779:49
    at EventEmitter.<anonymous> (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:9584:190)
    at EventEmitter.emit (node:events:538:35)
    at ExtEventHandler.emit (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:8308:197)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:4216:12
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)

**Comment by TanninOne** [comment]
@IDCs could you look into this?
