### ISSUE TITLE
libxmljs(2?) build problems

### ISSUE THREAD

**Issue by NicBOMB** [Nexus-Mods/Vortex#13414]
**Describe the bug**
The [version of libxmljs or libxmljs2 Vortex uses](https://github.com/TanninOne/libxmljs/tree/sambacha) is no longer building, at least on Linux, due to the latest electron updates.

**To Reproduce**
1. Enter vortex_devel
2. 
<details><summary>build log</summary>

```bash
$ yarn install
yarn install v1.22.19
$ git submodule update --init --recursive
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > fomod-installer@0.7.17" has incorrect peer dependency "winapi-bindings@Nexus-Mods/node-winapi-bindings".
warning " > modmeta-db@0.9.0" has incorrect peer dependency "commander@^6.1.0".
warning " > modmeta-db@0.9.0" has unmet peer dependency "express@^4.14.0".
warning "react-sortable-tree > frontend-collective-react-dnd-scrollzone@1.0.2" has incorrect peer dependency "react-dnd@^7.3.0".
warning "react-docgen-typescript-loader > @webpack-contrib/schema-utils@1.0.0-beta.0" has incorrect peer dependency "webpack@^3.0.0 || ^4.0.0".
warning " > tslint-eslint-rules@5.4.0" has incorrect peer dependency "typescript@^2.2.0 || ^3.0.0".
[4/4] Building fresh packages...
error /GitHub/Nexus-Mods/Vortex/node_modules/libxmljs: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --loglevel http
Arguments: 
Directory: /GitHub/Nexus-Mods/Vortex/node_modules/libxmljs
Output:
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp http GET https://github.com/marudor/libxmljs2/releases/download/v0.27.1/electron-v21.1-linux-x64-glibc.tar.gz
node-pre-gyp http 404 https://github.com/marudor/libxmljs2/releases/download/v0.27.1/electron-v21.1-linux-x64-glibc.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/marudor/libxmljs2/releases/download/v0.27.1/electron-v21.1-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for libxmljs2@0.27.1+nmfork and electron@21.1.0 (electron-v21.1 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/marudor/libxmljs2/releases/download/v0.27.1/electron-v21.1-linux-x64-glibc.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@19.0.0 | linux | x64
gyp info ok 
make: Entering directory '/GitHub/Nexus-Mods/Vortex/node_modules/libxmljs/build'
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
In file included from ~/.cache/node-gyp/21.1.0/include/node/v8-object.h:9,
                 from ~/.cache/node-gyp/21.1.0/include/node/v8-array-buffer.h:13,
                 from ~/.cache/node-gyp/21.1.0/include/node/v8.h:24,
                 from ../src/libxmljs.cc:3:
~/.cache/node-gyp/21.1.0/include/node/v8-maybe.h:106:45: error: ‘is_lvalue_reference_v’ is not a member of ‘std’; did you mean ‘is_lvalue_reference’?
  106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
      |                                             ^~~~~~~~~~~~~~~~~~~~~
      |                                             is_lvalue_reference
~/.cache/node-gyp/21.1.0/include/node/v8-maybe.h:106:66: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
  106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
      |                                                                  ^
~/.cache/node-gyp/21.1.0/include/node/v8-maybe.h:106:67: error: template argument 1 is invalid
  106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
      |                                                                   ^
~/.cache/node-gyp/21.1.0/include/node/v8-maybe.h:106:71: error: expected unqualified-id before ‘>’ token
  106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
      |                                                                       ^
~/.cache/node-gyp/21.1.0/include/node/v8-maybe.h:123:43: error: ‘is_lvalue_reference_v’ is not a member of ‘std’; did you mean ‘is_lvalue_reference’?
  123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
      |                                           ^~~~~~~~~~~~~~~~~~~~~
      |                                           is_lvalue_reference
~/.cache/node-gyp/21.1.0/include/node/v8-maybe.h:123:64: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
  123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
      |                                                                ^
~/.cache/node-gyp/21.1.0/include/node/v8-maybe.h:123:65: error: template argument 1 is invalid
  123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
      |                                                                 ^
~/.cache/node-gyp/21.1.0/include/node/v8-maybe.h:123:70: error: expected unqualified-id before ‘=’ token
  123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
      |                                                                      ^
In file included from ~/.cache/node-gyp/21.1.0/include/node/v8-object.h:10:
~/.cache/node-gyp/21.1.0/include/node/v8-persistent-handle.h:256:44: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
  256 |   using CopyablePersistent = Persistent<T, CopyablePersistentTraits<T>>;
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
~/.cache/node-gyp/21.1.0/include/node/v8-persistent-handle.h:255:48: note: declared here
  255 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ~/.cache/node-gyp/21.1.0/include/node/v8.h:62:
~/.cache/node-gyp/21.1.0/include/node/v8-wasm.h:192:34: warning: ‘Client’ is deprecated: Use SetMoreFunctionsCanBeSerializedCallback [-Wdeprecated-declarations]
  192 |   void SetClient(std::shared_ptr<Client> client);
      |                                  ^~~~~~
~/.cache/node-gyp/21.1.0/include/node/v8-wasm.h:137:70: note: declared here
  137 |   class V8_DEPRECATED("Use SetMoreFunctionsCanBeSerializedCallback") Client {
      |                                                                      ^~~~~~
In file included from ../src/libxmljs.h:5,
                 from ../src/libxmljs.cc:7:
../../nan/nan.h:206:16: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
  206 |     public v8::CopyablePersistentTraits<T> {};
      |                ^~~~~~~~~~~~~~~~~~~~~~~~
~/.cache/node-gyp/21.1.0/include/node/v8-persistent-handle.h:255:48: note: declared here
  255 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../nan/nan.h:60:
~/.cache/node-gyp/21.1.0/include/node/node.h:862:7: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  862 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~/.cache/node-gyp/21.1.0/include/node/node.h:896:3: note: in expansion of macro ‘NODE_MODULE_X’
  896 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/libxmljs.cc:250:1: note: in expansion of macro ‘NODE_MODULE’
  250 | NODE_MODULE(xmljs, init)
      | ^~~~~~~~~~~
make: *** [xmljs.target.mk:188: Release/obj.target/xmljs/src/libxmljs.o] Error 1
make: Leaving directory '/GitHub/Nexus-Mods/Vortex/node_modules/libxmljs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/GitHub/Nexus-Mods/Vortex/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Linux 6.0.2-zen1-1-zen
gyp ERR! command "/usr/bin/node" "/GitHub/Nexus-Mods/Vortex/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/GitHub/Nexus-Mods/Vortex/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/GitHub/Nexus-Mods/Vortex/node_modules/libxmljs/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v21.1"
gyp ERR! cwd /GitHub/Nexus-Mods/Vortex/node_modules/libxmljs
gyp ERR! node -v v19.0.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /GitHub/Nexus-Mods/Vortex/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/GitHub/Nexus-Mods/Vortex/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/GitHub/Nexus-Mods/Vortex/node_modules/libxmljs/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v21.1' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/GitHub/Nexus-Mods/Vortex/node_modules/@marudor/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
node-pre-gyp ERR! System Linux 6.0.2-zen1-1-zen
node-pre-gyp ERR! command "/usr/bin/node" "/GitHub/Nexus-Mods/Vortex/node_modules/libxmljs/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /GitHub/Nexus-Mods/Vortex/node_modules/libxmljs
node-pre-gyp ERR! node -v v19.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.16.1
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /GitHub/Nexus-Mods/Vortex/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/GitHub/Nexus-Mods/Vortex/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/GitHub/Nexus-Mods/Vortex/node_modules/libxmljs/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v21.1' (1)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

</details>

**Platform (please complete the following information):**
 - OS: Linux
 - Vortex Version: [lastest commit on master](https://github.com/Nexus-Mods/Vortex/commit/cde11e5ed127783f25a9a61dc67922af3c8cb5d6)

**Additional context**
> [regarding libxmljs: Vortex doesn't actually use that library any more because it's been a growing pain in the ass for us.
The only reason we still ship it is for the possibility that a third-party extension may be built on it, since we don't want to break backwards compatibility.
There is a fairly good reason you could drop it from the linux build and no one would care.](https://github.com/Nexus-Mods/Vortex/pull/13109#issuecomment-1253303971)

At some point, libxmljs(2) should be removed from Vortex's build process completely. I'm unsure about dropping it from the Linux build specifically; it doesn't seem as simple as removing the module from `package.json` and adding `src/util/libxmljs.ts` to an exclude in `ts.config`.

**Comment by TanninOne** [comment]
The promise we give extension developers by using semantic versioning is that no minor update with break backwards compatibility. Hence libxmljs can not be dropped from the main development branch until we do a Vortex 2.0.0 release but that release would have to do more breaking changes/improvements to justify that release and while there are considerations for that I wouldn't be surprised if it takes another couple of years.
If you can't build libxmljs for linux now then having a separate code path is the only option.

**Comment by sparr** [comment]
Adding `'cflags_cc': [ '-std=c++17' ],` to the first (and only) target in node_modules/libxmljs/binding.gyp will result in node-gyp being able to complete the build.

**Comment by TanninOne** [comment]
@NicBOMB I've updated our libxmljs fork (version "0.27.2+nmfork") with that change, please check if that works.
