### ISSUE TITLE
Failed to load master-/userlist

### ISSUE THREAD

**Issue by oopsadaisy** [Nexus-Mods/Vortex#13458]
ENOENT: no such file or directory, stat 'C:\Users\graha\AppData\Roaming\Vortex\fallout4\masterlist\masterlist.yaml'
Error
    at Object.statAsync (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:9072:216)
    at t.default.<anonymous> (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:2:631882)
![Screenshot 2022-11-06 113247](https://user-images.githubusercontent.com/69156600/200168166-1da2a0cc-3e5a-49fe-acba-3b9d1956b688.png)

**Comment by marcopics** [comment]
Hello, after a long time, this error still persists. I'm not an expert in this field, so I hope this reaches whoever was able to fix it.

P.S. I don't speak English very well either. If you notice errors, it's my fault. :)


ENOENT: no such file or directory, stat 'C:\Users\imaxm\AppData\Roaming\Vortex\fallout4\masterlist\masterlist.yaml'
ENOENT: no such file or directory, stat 'C:\Users\imaxm\AppData\Roaming\Vortex\fallout4\masterlist\masterlist.yaml'
Error: ENOENT: no such file or directory, stat 'C:\Users\imaxm\AppData\Roaming\Vortex\fallout4\masterlist\masterlist.yaml'
Prior Context:
    at Object.statAsync (D:\Vortexapp\resources\app.asar\renderer.js:9664:27)
    at t.default.<anonymous> (D:\Vortexapp\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:2:633489)
Prior Context:
    at Object.statAsync (D:\Vortexapp\resources\app.asar\renderer.js:9664:27)
    at t.default.<anonymous> [(D:\Vortexapp\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:2:633489)]

a sample of the error...

![Image](https://github.com/user-attachments/assets/5d0af8f6-3d5f-410f-bdd4-b8b513ef3dbc)
