### ISSUE TITLE
Failed to set game mode - happens to Spider-man remastered and miles morales too

### ISSUE THREAD

**Issue by dyonkus** [Nexus-Mods/Vortex#13577]
TypeError: api.ext.nexusGetModFiles is not a function
    at C:\Users\dyonk\AppData\Roaming\Vortex\plugins\Vortex Extension Update - Spider-Man Remastered and Miles Morales Support v2.0.1\index.js:760:40
    at Generator.next (<anonymous>)
    at C:\Users\dyonk\AppData\Roaming\Vortex\plugins\Vortex Extension Update - Spider-Man Remastered and Miles Morales Support v2.0.1\index.js:625:71
    at Promise.cancellationExecute [as _execute] (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\debuggability.js:406:9)
    at Promise._resolveFromExecutor (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:518:18)
    at new Promise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:103:10)
    at __webpack_modules__.e:\WorkC\extensions\game-marvelsspidermanremastered\src\toolIntegration.ts.__awaiter (C:\Users\dyonk\AppData\Roaming\Vortex\plugins\Vortex Extension Update - Spider-Man Remastered and Miles Morales Support v2.0.1\index.js:621:12)
    at download (C:\Users\dyonk\AppData\Roaming\Vortex\plugins\Vortex Extension Update - Spider-Man Remastered and Miles Morales Support v2.0.1\index.js:759:12)
    at C:\Users\dyonk\AppData\Roaming\Vortex\plugins\Vortex Extension Update - Spider-Man Remastered and Miles Morales Support v2.0.1\index.js:678:51
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\dyonk\AppData\Roaming\Vortex\plugins\Vortex Extension Update - Spider-Man Remastered and Miles Morales Support v2.0.1\index.js:622:58)
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)

**Comment by TanninOne** [comment]
Sorry about that, the 2.0.1 release uses functionality from Vortex core that hasn't actually been released yet...
2.0.2 should fix this.

**Comment by dyonkus** [comment]
> Sorry about that, the 2.0.1 release uses functionality from Vortex core that hasn't actually been released yet... 2.0.2 should fix this.

when will 2.0.2 be released?
