### ISSUE TITLE
Witcher 3 Game Extension will not install due to github connection timeout.

### ISSUE THREAD

**Issue by HazeyDays** [Nexus-Mods/Vortex#13683]
**Describe the bug**
Can't update Witcher 3 Game extension from GitHub.

**To Reproduce**
1. Start Vortex with Witcher 3 profile in view.
2. Wait for extension to update
3. Click Extensions
4. See indication to restart to Update Extension (that wasn't installed).

**Expected behavior**
Witcher 3 Game extension to install from github.

**Platform (please complete the following information):**
 - OS: Win11
 - Vortex Version: v1.6.14 and v1.7.2beta

**Additional context**
connect ETIMEDOUT 185.199.111.133:443
connect ETIMEDOUT 185.199.111.133:443
Error: connect ETIMEDOUT 185.199.111.133:443
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:643:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
Prior Context:
    at Object.withTmpDir (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:9369:27)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:2675:180
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)
Prior Context:
    at Object.withTmpDir (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:9369:27)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:2675:180
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)

**Comment by TanninOne** [comment]
network issues are out of our control, try it again later.

**Comment by HaHeho** [comment]
I had the same issue on both Vortex versions (Win10 instead). Disabling VPN fixed it for me.

**Comment by HazeyDays** [comment]
> I had the same issue on both Vortex versions (Win10 instead). Disabling VPN fixed it for me.

OK, I'll just forgo the use of Vortex modding for the Witcher if that's the cause.
Disabling is not an option for me. Thanks, anyway. I'll still keep your remedy in mind.
