### ISSUE TITLE
Vortex game ext issue - TypeError: Invalid Version: 1.0

### ISSUE THREAD

**Issue by M0nsh3r1** [Nexus-Mods/Vortex#14469]
**Describe the bug**
Dungeon Siege 2 extension doesn't want to load.

```
TypeError: Invalid Version: 1.0
    at new SemVer (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\semver\classes\semver.js:38:13)
    at compare (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\semver\functions\compare.js:3:3)
    at Object.gte (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\semver\functions\gte.js:2:30)
    at context.registerGame [as callback] (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:3071:19)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:8619:203
    at Array.forEach (<anonymous>)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:8619:96
    at Array.forEach (<anonymous>)
    at ContextProxyHandler.invokeAdditions (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:8619:48)
    at ExtensionManager.applyExtensionsOfExtensions (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:8678:214)
    at init (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:8330:114)
    at 8052 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:8345:136)
    at __webpack_require__ (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:10557:39)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:10560:71
    at Object.<anonymous> (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:10560:133)
    at Object.<anonymous> (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:10562:3)
```

**To Reproduce**
1. Go to Games
2. Click on Dungeon Siege 2 ext and install it
3. Restart Vortex
4. See error in the notification tab 
5. Game find and load in vortex doesn't work 

**Expected behavior**
Install game ext and it will find my already installed Dungeon Siege 2 on my PC. But for now, my installed game is missing in "manage" vortex tab. 

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 11 x64
 - Vortex Version 1.8.5
![image](https://github.com/Nexus-Mods/Vortex/assets/94806597/9004f64a-862f-4e23-82af-2d30d1690d51)

**Comment by Woffenhorst** [comment]
@M0nsh3r1 
It seems to be a bug with the extension itself, it's easy to fix yourself. Navigate to %AppData%\Vortex\plugins (you can type this into windows explorer, %AppData% gets replaced with c:\Users<account name>\AppData\Roaming). Then open the folder for DS2 extension and edit the info.json file and change the version from "1.0" to "1.0.0". Vortex uses a 3 number version system, and therefore thinks "1.0" is invalid.

I have informed the maker of the extension, so hopefully it will be fixed soon.
