### ISSUE TITLE
LSLIB Failure to install on Vortex

### ISSUE THREAD

**Issue by herpacin** [Nexus-Mods/Vortex#14554]
LSLIB fails to load for BG3 mod support:

![image](https://github.com/Nexus-Mods/Vortex/assets/141375425/a8ac2f2a-9d75-4875-9694-c9805e5bbd75)
![image](https://github.com/Nexus-Mods/Vortex/assets/141375425/d03061b7-4aec-4c54-a658-7e71e313941f)

Connectivity is not an issue as mods will download, tested the URL contained in the plugin and its live.

Error Text: 
DataInvalid: Failed to resolve browser download url
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\game-baldursgate3\githubDownloader.js:214:30
    at Generator.next (<anonymous>)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\game-baldursgate3\githubDownloader.js:31:71
    at Promise.cancellationExecute [as _execute] (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\debuggability.js:406:9)
    at Promise._resolveFromExecutor (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:518:18)
    at new Promise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:103:10)
    at __awaiter (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\game-baldursgate3\githubDownloader.js:27:12)
    at resolveDownloadLink (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\game-baldursgate3\githubDownloader.js:210:12)
    at Object.<anonymous> (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\game-baldursgate3\githubDownloader.js:257:40)
    at Generator.next (<anonymous>)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\game-baldursgate3\githubDownloader.js:31:71
    at Promise.cancellationExecute [as _execute] (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\debuggability.js:406:9)
    at Promise._resolveFromExecutor (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:518:18)
    at new Promise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:103:10)
    at __awaiter (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\game-baldursgate3\githubDownloader.js:27:12)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\game-baldursgate3\githubDownloader.js:256:40

Windows 11
Vortex version 1.85

**Comment by stephanrb3** [comment]
I'm also seeing this error, but I'm not quite clear on how to install this manually.
