### ISSUE TITLE
ENOENT: no such file or directory, open...7z-bin\package.json

### ISSUE THREAD

**Issue by IDCs** [Nexus-Mods/Vortex#1466]
#### System
| | |
|------------ | -------------|
|Platform | win32 10.0.17134 |
|Architecture | x64 |
|Application Version | 0.16.8 |
|Process | browser |
#### Message
Startup failed
#### Details
```
ENOENT: no such file or directory, open 'E:\Vortex\resources\app.asar.unpacked\node_modules\7z-bin\package.json'
```
#### Stack
```
Error: ENOENT: no such file or directory, open 'E:\Vortex\resources\app.asar.unpacked\node_modules\7z-bin\package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at process.binding.internalModuleReadFile (ELECTRON_ASAR.js:640:19)
    at readPackage (module.js:118:16)
    at tryPackage (module.js:135:13)
    at Function.Module._findPath (module.js:217:20)
    at Module._resolveFilename (module.js:541:25)
    at Function.Module._resolveFilename (E:\Vortex\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at Module.require (E:\Vortex\resources\app.asar\webpack:\src\index.ts:7:1)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Vortex\resources\app.asar\node_modules\node-7z\util\run7z.js:1:104)
    at Object.<anonymous> (E:\Vortex\resources\app.asar\node_modules\node-7z\util\run7z.js:20:3)
```

 Justv clicked on icon to start  vortex ,thats all.It keeps crashing. Ive teried to reinsatll but same issue. 
 
 Reported by: Anonymous

_Originally posted by @VortexFeedback in https://github.com/Nexus-Mods/Vortex/issues/146#issuecomment-430523708_

**Comment by TanninOne** [comment]
I believe this could only happen in a broken custom build or damaged install archive.
