### ISSUE TITLE
Unexpected token � in JSON at position 0

### ISSUE THREAD

**Issue by IDCs** [Nexus-Mods/Vortex#1467]
#### System
| | |
|------------ | -------------|
|Platform | win32 10.0.17134 |
|Architecture | x64 |
|Application Version | 0.16.8 |
|Process | renderer |
#### Message
Unexpected token � in JSON at position 0
#### Stack
```
SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at dat (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\webpack:\src\extensions\nexus_integration\util\chromePath.ts:32:12)
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:582:21)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:638:18)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\nodeback.js:42:21
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

  
 
 Reported by: Anonymous

_Originally posted by @VortexFeedback in https://github.com/Nexus-Mods/Vortex/issues/146#issuecomment-430523834_

**Comment by TanninOne** [comment]
Should be fixed by 7268f4ffaac509cc327a3735547c6102fe7a6700
