### ISSUE TITLE
Looped failed extension installation. (Stardew Valley github error)

### ISSUE THREAD

**Issue by Shituation** [Nexus-Mods/Vortex#14675]
**Describe the bug**
An error poping up on every vortex start saying:
`"failed to install extension "Game:Stardew Valley" from "github.com"`

**To Reproduce**
Open vortex and wait a couple of seconds.

**Screenshots**

![2023-09-10 11-11-21](https://github.com/Nexus-Mods/Vortex/assets/43975882/dfb11ebc-deac-4291-bbbc-93eac4db4c51)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version [e.g. 0.16.12]

**Additional context**
```
connect ETIMEDOUT 185.199.111.133:443
connect ETIMEDOUT 185.199.111.133:443
Error: connect ETIMEDOUT 185.199.111.133:443
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:668:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
Prior Context:
    at Object.withTmpDir (D:\Mods\Vortex\APP\resources\app.asar\renderer.js:9456:27)
    at D:\Mods\Vortex\APP\resources\app.asar\renderer.js:2723:180
    at tryCatcher (D:\Mods\Vortex\APP\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Mods\Vortex\APP\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\Mods\Vortex\APP\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (D:\Mods\Vortex\APP\resources\app.asar\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (D:\Mods\Vortex\APP\resources\app.asar\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (D:\Mods\Vortex\APP\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\Mods\Vortex\APP\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (D:\Mods\Vortex\APP\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)
Prior Context:
    at Object.withTmpDir (D:\Mods\Vortex\APP\resources\app.asar\renderer.js:9456:27)
    at D:\Mods\Vortex\APP\resources\app.asar\renderer.js:2723:180
    at tryCatcher (D:\Mods\Vortex\APP\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Mods\Vortex\APP\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\Mods\Vortex\APP\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (D:\Mods\Vortex\APP\resources\app.asar\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (D:\Mods\Vortex\APP\resources\app.asar\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (D:\Mods\Vortex\APP\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\Mods\Vortex\APP\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (D:\Mods\Vortex\APP\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)

```

**Comment by ThePrivacyPlayer** [comment]
This is still an issue. I get the error everytime I open up Vortex, and I never bought or installed any version of Stardew Valley. It's not in my managed games either.

I tried hiding the game, but the issue persists. It's extremely annoying and caused another issue where, when launching Skyrim before the error pops up, it opened on the wrong monitor (I have multiple monitors) with weird graphical bugs.

This is very annoying.

**Comment by Thaeral** [comment]
Just adding that I have this as well.  I actually own, mod, and play Stardew. It does not prevent me from playing or continuing to mod Stardew.

System Details:
```
OS: Windows 11 Pro
Version: 23H2
Build: 22631.3527
```

Vortex Details:
`Version: Stable 1.10.8`

Error Details:
```
connect ETIMEDOUT 185.199.109.133:443
connect ETIMEDOUT 185.199.109.133:443
Error: connect ETIMEDOUT 185.199.109.133:443
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:668:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
Prior Context:
    at Object.withTmpDir (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:9482:27)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:2725:180
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)
Prior Context:
    at Object.withTmpDir (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:9482:27)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:2725:180
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)
```
