### ISSUE TITLE
Unhandled Error in Event "will-deploy" and "did-deploy"  FFXII  Managing

### ISSUE THREAD

**Issue by Glurak18** [Nexus-Mods/Vortex#15296]
When i try to say manage FF XII both error happen:

TypeError: Cannot read properties of undefined (reading 'path')
    at checkExternalLoader (C:\ProgramData\vortex\plugins\Vortex Extension Update - Final Fantasy XII The Zodiac Age Vortex support v0.8.4\game-merged.js:90:41)
    at C:\ProgramData\vortex\plugins\Vortex Extension Update - Final Fantasy XII The Zodiac Age Vortex support v0.8.4\game-merged.js:262:12
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:10032:35
    at EventEmitter.<anonymous> (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:8818:15)
    at EventEmitter.emit (node:events:525:35)
    at Proxy.emitAndAwait (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:8815:28)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:4858:227
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)

 And the second :
 
 TypeError: Cannot read properties of undefined (reading 'path')
    at checkExternalLoader (C:\ProgramData\vortex\plugins\Vortex Extension Update - Final Fantasy XII The Zodiac Age Vortex support v0.8.4\game-merged.js:90:41)
    at C:\ProgramData\vortex\plugins\Vortex Extension Update - Final Fantasy XII The Zodiac Age Vortex support v0.8.4\game-merged.js:274:12
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:10032:35
    at EventEmitter.<anonymous> (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:8818:15)
    at EventEmitter.emit (node:events:525:35)
    at Proxy.emitAndAwait (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:8815:28)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:4883:79
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)

**Comment by IDCs** [comment]
Hi there - the FFXII extension is developed and maintained by members of the community - please report this to the developers of the extension on their page on Nexus Mods.
