### ISSUE TITLE
Vortex cannot deploy mods for Warhammer 40k: Darktide

### ISSUE THREAD

**Issue by jeffthehatfield** [Nexus-Mods/Vortex#16753]
**Describe the bug**
Error when deploying. No matter if mods are Enabled, Installed, or anything. Any time I deploy I get the below error

TypeError: The "path" argument must be of type string. Received null
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at join (node:path:429:7)
    at path.join (G:\Program Files\Vortex\resources\app.asar\renderer.js:9956:122)
    at C:\Users\***\AppData\Roaming\Vortex\plugins\Warhammer 40k Darktide-684-1-5-3-1731193769\index.js:507:16
    at G:\Program Files\Vortex\resources\app.asar\renderer.js:10191:35
    at EventEmitter.<anonymous> (G:\Program Files\Vortex\resources\app.asar\renderer.js:8970:15)
    at EventEmitter.emit (node:events:529:35)
    at Proxy.emitAndAwait (G:\Program Files\Vortex\resources\app.asar\renderer.js:8967:28)
    at G:\Program Files\Vortex\resources\app.asar\renderer.js:4964:79
    at tryCatcher (G:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (G:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (G:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (G:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (G:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (G:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (G:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (G:\Program Files\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.13.2

**Comment by IDCs** [comment]
Hi @jeffthehatfield - the darktide extension is written by the community. Please report this to the extension author on his extension page.
https://www.nexusmods.com/site/mods/684
