### ISSUE TITLE
无法安装扩展

### ISSUE THREAD

**Issue by Gentry1129** [Nexus-Mods/Vortex#16901]
connect ETIMEDOUT 2606:50c0:8003::154:443
connect ETIMEDOUT 2606:50c0:8003::154:443
Error: connect ETIMEDOUT 2606:50c0:8003::154:443
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
Prior Context:
    at Object.withTmpDir (C:\Vortex\resources\app.asar\renderer.js:9649:27)
    at C:\Vortex\resources\app.asar\renderer.js:2745:180
    at tryCatcher (C:\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)
Prior Context:
    at Object.withTmpDir (C:\Vortex\resources\app.asar\renderer.js:9649:27)
    at C:\Vortex\resources\app.asar\renderer.js:2745:180
    at tryCatcher (C:\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Vortex\resources\app.asar\node_modules\bluebird

**Comment by IDCs** [comment]
Hi there - this error is usually temporary; if it's consistent, please report it to support@nexusmods.com - we (Vortex team) can't assist in debugging connectivity issues.
