### ISSUE TITLE
Failed to set game mode

### ISSUE THREAD

**Issue by Tbknight691** [Nexus-Mods/Vortex#6135]
Vortex version: 1.2.7
OS: Windows 8.1 64bits

When trying to activate Kingdom Come Delivrance game mode, it failed to it and sent me the error message: "Failed to set gamemode"

In the more section is written: 

TypeError: data.split is not a function
    at E:\Vortex\resources\app.asar.unpacked\bundledPlugins\game-kingdomcome-deliverance\index.js:33:58
    at tryCatcher (E:\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (E:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)

The icon of Kingdom Come Delivrance appears and instantly disappear from topscreen.

Is there a way to repair this?

**Comment by IDCs** [comment]
Hi @Tbknight691, thanks for your report - we did notice that issue and had fixed it in https://github.com/Nexus-Mods/vortex-games/commit/b3199a1334499bc14340e9275cf11ced344ccec0

We're going to release a fix for it soon.
