### ISSUE TITLE
Error - node - Linux

### ISSUE THREAD

**Issue by Desulate** [Nexus-Mods/Vortex#6156]
**Describe the bug**
A bug related to node

Launch the game, then receive error output:

net.js:314
      err = this._handle.open(fd);
                         ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:314:26)
    at createWritableStdioStream (internal/process/stdio.js:179:18)
    at process.getStdout [as stdout] (internal/process/stdio.js:28:14)
    at Object.<anonymous> (electron/js2c/browser_init.js:5669:13)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:5824:30)
    at __webpack_require__ (electron/js2c/browser_init.js:20:30)
    at electron/js2c/browser_init.js:84:18
    at electron/js2c/browser_init.js:87:10
    at NativeModule.compile (internal/bootstrap/loaders.js:287:5)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:222:8) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'uv_pipe_open'
}

**Expected behavior**
Vortex fails to launch

**Screenshots**

**Platform (please complete the following information):**
Linux (wine)
Vortex Version 1.2.9

**Additional context**
Linux nor wine should be the issue, I've also submitted a report to the author of the lutris installer for vortex, so that they can look into it as well. https://github.com/rockerbacon/lutris-skyrimse-installers

**Comment by TanninOne** [comment]
We don't support Linux.

The problem is practically guaranteed to be wine. The error happens completely under the hood, no Vortex code is even involved here.
What happens is that node tries to open a stdout stream to write to (probably to log something) and that fails on an OS level. So it's definitively between Wine and Linux. It may be that some kind of security settings are interfering here.
