### ISSUE TITLE
Unknown Error while installing mods

### ISSUE THREAD

**Issue by chkklehed** [Nexus-Mods/Vortex#6276]
While attempting to install any mod downloaded from the nexus, I am met with the following error:

Error: unknown error: [   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at FomodInstaller.Scripting.ScriptTypeRegistry.<>c__DisplayClass1_0.<RegisterScriptTypes>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FomodInstaller.Scripting.ScriptTypeRegistry.<RegisterScriptTypes>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FomodInstaller.Scripting.ScriptTypeRegistry.<DiscoverScriptTypes>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FomodInstaller.ModInstaller.ModFormatManager.<GetRequirements>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FomodInstaller.ModInstaller.Installer.<GetRequirements>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FomodInstaller.ModInstaller.Installer.<TestSupported>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModInstallerIPC.Server.<DispatchTestSupported>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModInstallerIPC.Server.<Dispatch>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModInstallerIPC.Server.<>c__DisplayClass21_0.<<OnReceived>b__0>d.MoveNext()] {
  name: 'System.BadImageFormatException'
}
    at transformError (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:4667:119)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:4692:221
    at Generator.throw (<anonymous>)
    at rejected (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:4646:71)

**Comment by IDCs** [comment]
Hi @chkklehed, I assume you were using Vortex 1.2.11 ?

Can you please attach your vortex.log files to the github issue. You can find them inside %appdata%/vortex.

**Comment by TanninOne** [comment]
The error message System.BadImageFormatException indicates that one of the files that shipped with Vortex or one that was shipped with .Net has been corrupted. Please reinstall Vortex, if that doesn't help, reinstall .Net.
